[[IGLWrap]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "74a2e5f4fc4c0c60f7195a84f623d8d13dfa4468"
libc = "glibc"
os = "linux"

    [[IGLWrap.download]]
    sha256 = "ac154bbc729f131fa22b67202bfba0059bbe188b6cac7ae91dd1238e50402e15"
    url = "https://github.com/plut/IGLWrap_jll.jl/releases/download/IGLWrap-v0.1.0+0/IGLWrap.v0.1.0.x86_64-linux-gnu-cxx03.tar.gz"
[[IGLWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "72e801fcdc9b271a803de0097dace55653598e91"
libc = "glibc"
os = "linux"

    [[IGLWrap.download]]
    sha256 = "304550a0105024d543051551569ec29bc8d717079ceae5aa0aca6cc7e780e259"
    url = "https://github.com/plut/IGLWrap_jll.jl/releases/download/IGLWrap-v0.1.0+0/IGLWrap.v0.1.0.x86_64-linux-gnu-cxx11.tar.gz"
