[[IGLWrap]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7db695957a8966fcf73a3154b96e633b59775b60"
libc = "glibc"
os = "linux"

    [[IGLWrap.download]]
    sha256 = "c1e2570737c4fbf120e28e2d63a8df9c24a4232df9c7907b7965596834325ef6"
    url = "https://github.com/plut/IGLWrap_jll.jl/releases/download/IGLWrap-v0.1.2+0/IGLWrap.v0.1.2.x86_64-linux-gnu-cxx03.tar.gz"
[[IGLWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "19cb909d423d39e932b9643f288bc50b9a731c9b"
libc = "glibc"
os = "linux"

    [[IGLWrap.download]]
    sha256 = "ad23990159204b5e028c83b89efffb0aafffcaa73710c03cc872c08a129af0c5"
    url = "https://github.com/plut/IGLWrap_jll.jl/releases/download/IGLWrap-v0.1.2+0/IGLWrap.v0.1.2.x86_64-linux-gnu-cxx11.tar.gz"
