[[IGLWrap]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2bbcc2f068a702c2466548db0eb31b57de4c1632"
libc = "glibc"
os = "linux"

    [[IGLWrap.download]]
    sha256 = "96d21ecb9e42b9f854052c8d41449dc0bdd71a1371b224e4edadca119a33de68"
    url = "https://github.com/plut/IGLWrap_jll.jl/releases/download/IGLWrap-v0.1.0+0/IGLWrap.v0.1.0.x86_64-linux-gnu-cxx03.tar.gz"
[[IGLWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "adff09ab4429f9c1270c328dba75dc92ef8c362d"
libc = "glibc"
os = "linux"

    [[IGLWrap.download]]
    sha256 = "7a01884cdfd78d63e05fceefafa09e79d72f3190c36aa47cc1bf4bb1e49fc88e"
    url = "https://github.com/plut/IGLWrap_jll.jl/releases/download/IGLWrap-v0.1.0+0/IGLWrap.v0.1.0.x86_64-linux-gnu-cxx11.tar.gz"
