[[IGLWrap]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4ab22c644c9c2e733b63ade00f736cd372947ea4"
libc = "glibc"
os = "linux"

    [[IGLWrap.download]]
    sha256 = "5aefa1a1f166cc3c349acab7cc13dfc8621b9acca3e7f3fe9c079bcee48dd5af"
    url = "https://github.com/plut/IGLWrap_jll.jl/releases/download/IGLWrap-v0.0.1+0/IGLWrap.v0.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[IGLWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "317a360d16897d62726a52e4acc1663d9503780e"
libc = "glibc"
os = "linux"

    [[IGLWrap.download]]
    sha256 = "5fe378fb844337d5dfdff24c41f7653f15aa3708feef5ffd33372bd34c49c1f9"
    url = "https://github.com/plut/IGLWrap_jll.jl/releases/download/IGLWrap-v0.0.1+0/IGLWrap.v0.0.1.x86_64-linux-gnu-cxx11.tar.gz"
