[[IGLWrap]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "994e125913aeba7aa25fe33a29de0aacc88f4e6f"
libc = "glibc"
os = "linux"

    [[IGLWrap.download]]
    sha256 = "01261e485a61ad65e9b6b06c666b809af7f16ef67b2b36fb3ad692fc9aa891f7"
    url = "https://github.com/plut/IGLWrap_jll.jl/releases/download/IGLWrap-v0.1.3+0/IGLWrap.v0.1.3.x86_64-linux-gnu-cxx03.tar.gz"
[[IGLWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "58fbd6e3ce418b09fb785f42a3047779dac0162c"
libc = "glibc"
os = "linux"

    [[IGLWrap.download]]
    sha256 = "ed8997d07ea58ae4e843447b7e12eec9f469613e2ca8fcd80d01dc69df2c075e"
    url = "https://github.com/plut/IGLWrap_jll.jl/releases/download/IGLWrap-v0.1.3+0/IGLWrap.v0.1.3.x86_64-linux-gnu-cxx11.tar.gz"
