[[IGLWrap]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "85b2079fa705996587a93ff7aaef78a0ad4f608a"
libc = "glibc"
os = "linux"

    [[IGLWrap.download]]
    sha256 = "02a84aff55f121901637fa6525a58d9fe5c22153d67022d95d0bccd6eedec47a"
    url = "https://github.com/plut/IGLWrap_jll.jl/releases/download/IGLWrap-v0.1.0+1/IGLWrap.v0.1.0.x86_64-linux-gnu-cxx03.tar.gz"
[[IGLWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1273355ba7758185e7755f771bd68ed36029fbb9"
libc = "glibc"
os = "linux"

    [[IGLWrap.download]]
    sha256 = "07c3aa849a5a9637c3cc0833d42e9847289d2db56a66df9a253023cf08d164ba"
    url = "https://github.com/plut/IGLWrap_jll.jl/releases/download/IGLWrap-v0.1.0+1/IGLWrap.v0.1.0.x86_64-linux-gnu-cxx11.tar.gz"
