[[IGLWrap]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c484f6c88462f5fb52bc550b0d3a01a5538781ba"
libc = "glibc"
os = "linux"

    [[IGLWrap.download]]
    sha256 = "bcb8ff13191049189fe3828aec3c3159a4a5ee803648c1c97ffb754b97483997"
    url = "https://github.com/plut/IGLWrap_jll.jl/releases/download/IGLWrap-v0.1.0+0/IGLWrap.v0.1.0.x86_64-linux-gnu-cxx03.tar.gz"
[[IGLWrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "da4854180e860ea44856f1c8672b9697e1840ad9"
libc = "glibc"
os = "linux"

    [[IGLWrap.download]]
    sha256 = "c9e8f4723235f2ccc3500fdcfec91a9145dbf34d76b563ea7837a3befd822bd6"
    url = "https://github.com/plut/IGLWrap_jll.jl/releases/download/IGLWrap-v0.1.0+0/IGLWrap.v0.1.0.x86_64-linux-gnu-cxx11.tar.gz"
