# Autogenerated wrapper script for IGLWrap_jll for x86_64-linux-gnu-cxx03
export libiglwrap

using boost_jll
using GMP_jll
using MPFR_jll
using OpenBLAS_jll
JLLWrappers.@generate_wrapper_header("IGLWrap")
JLLWrappers.@declare_library_product(libiglwrap, "libiglwrap.so")
function __init__()
    JLLWrappers.@generate_init_header(boost_jll, GMP_jll, MPFR_jll, OpenBLAS_jll)
    JLLWrappers.@init_library_product(
        libiglwrap,
        "lib/libiglwrap.so",
        RTLD_NOW | RTLD_LOCAL,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
