# Autogenerated wrapper script for IGLWrap_jll for x86_64-linux-gnu-cxx11
using boost_jll
using GMP_jll
using MPFR_jll
using OpenBLAS_jll
JLLWrappers.@generate_wrapper_header("IGLWrap")
function __init__()
    JLLWrappers.@generate_init_header(boost_jll, GMP_jll, MPFR_jll, OpenBLAS_jll)
    JLLWrappers.@generate_init_footer()
end  # __init__()
